// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createEntryStmt, err = db.PrepareContext(ctx, createEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEntry: %w", err)
	}
	if q.createTransferStmt, err = db.PrepareContext(ctx, createTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransfer: %w", err)
	}
	if q.deleteAccountStmt, err = db.PrepareContext(ctx, deleteAccount); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccount: %w", err)
	}
	if q.deleteEntryStmt, err = db.PrepareContext(ctx, deleteEntry); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteEntry: %w", err)
	}
	if q.deleteTransferStmt, err = db.PrepareContext(ctx, deleteTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTransfer: %w", err)
	}
	if q.getAccountStmt, err = db.PrepareContext(ctx, getAccount); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccount: %w", err)
	}
	if q.getEntryStmt, err = db.PrepareContext(ctx, getEntry); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntry: %w", err)
	}
	if q.getTransferStmt, err = db.PrepareContext(ctx, getTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransfer: %w", err)
	}
	if q.listAccountStmt, err = db.PrepareContext(ctx, listAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccount: %w", err)
	}
	if q.listEntriesByAccountStmt, err = db.PrepareContext(ctx, listEntriesByAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ListEntriesByAccount: %w", err)
	}
	if q.listTransfersBetweenAccountsStmt, err = db.PrepareContext(ctx, listTransfersBetweenAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransfersBetweenAccounts: %w", err)
	}
	if q.listTransfersFromAccountStmt, err = db.PrepareContext(ctx, listTransfersFromAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransfersFromAccount: %w", err)
	}
	if q.listTransfersToAccountStmt, err = db.PrepareContext(ctx, listTransfersToAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransfersToAccount: %w", err)
	}
	if q.updateAccountStmt, err = db.PrepareContext(ctx, updateAccount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccount: %w", err)
	}
	if q.updateEntryStmt, err = db.PrepareContext(ctx, updateEntry); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateEntry: %w", err)
	}
	if q.updateTransferStmt, err = db.PrepareContext(ctx, updateTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTransfer: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createEntryStmt != nil {
		if cerr := q.createEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEntryStmt: %w", cerr)
		}
	}
	if q.createTransferStmt != nil {
		if cerr := q.createTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransferStmt: %w", cerr)
		}
	}
	if q.deleteAccountStmt != nil {
		if cerr := q.deleteAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccountStmt: %w", cerr)
		}
	}
	if q.deleteEntryStmt != nil {
		if cerr := q.deleteEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteEntryStmt: %w", cerr)
		}
	}
	if q.deleteTransferStmt != nil {
		if cerr := q.deleteTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTransferStmt: %w", cerr)
		}
	}
	if q.getAccountStmt != nil {
		if cerr := q.getAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountStmt: %w", cerr)
		}
	}
	if q.getEntryStmt != nil {
		if cerr := q.getEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntryStmt: %w", cerr)
		}
	}
	if q.getTransferStmt != nil {
		if cerr := q.getTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransferStmt: %w", cerr)
		}
	}
	if q.listAccountStmt != nil {
		if cerr := q.listAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccountStmt: %w", cerr)
		}
	}
	if q.listEntriesByAccountStmt != nil {
		if cerr := q.listEntriesByAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEntriesByAccountStmt: %w", cerr)
		}
	}
	if q.listTransfersBetweenAccountsStmt != nil {
		if cerr := q.listTransfersBetweenAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransfersBetweenAccountsStmt: %w", cerr)
		}
	}
	if q.listTransfersFromAccountStmt != nil {
		if cerr := q.listTransfersFromAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransfersFromAccountStmt: %w", cerr)
		}
	}
	if q.listTransfersToAccountStmt != nil {
		if cerr := q.listTransfersToAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransfersToAccountStmt: %w", cerr)
		}
	}
	if q.updateAccountStmt != nil {
		if cerr := q.updateAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountStmt: %w", cerr)
		}
	}
	if q.updateEntryStmt != nil {
		if cerr := q.updateEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateEntryStmt: %w", cerr)
		}
	}
	if q.updateTransferStmt != nil {
		if cerr := q.updateTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTransferStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	createAccountStmt                *sql.Stmt
	createEntryStmt                  *sql.Stmt
	createTransferStmt               *sql.Stmt
	deleteAccountStmt                *sql.Stmt
	deleteEntryStmt                  *sql.Stmt
	deleteTransferStmt               *sql.Stmt
	getAccountStmt                   *sql.Stmt
	getEntryStmt                     *sql.Stmt
	getTransferStmt                  *sql.Stmt
	listAccountStmt                  *sql.Stmt
	listEntriesByAccountStmt         *sql.Stmt
	listTransfersBetweenAccountsStmt *sql.Stmt
	listTransfersFromAccountStmt     *sql.Stmt
	listTransfersToAccountStmt       *sql.Stmt
	updateAccountStmt                *sql.Stmt
	updateEntryStmt                  *sql.Stmt
	updateTransferStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		createAccountStmt:                q.createAccountStmt,
		createEntryStmt:                  q.createEntryStmt,
		createTransferStmt:               q.createTransferStmt,
		deleteAccountStmt:                q.deleteAccountStmt,
		deleteEntryStmt:                  q.deleteEntryStmt,
		deleteTransferStmt:               q.deleteTransferStmt,
		getAccountStmt:                   q.getAccountStmt,
		getEntryStmt:                     q.getEntryStmt,
		getTransferStmt:                  q.getTransferStmt,
		listAccountStmt:                  q.listAccountStmt,
		listEntriesByAccountStmt:         q.listEntriesByAccountStmt,
		listTransfersBetweenAccountsStmt: q.listTransfersBetweenAccountsStmt,
		listTransfersFromAccountStmt:     q.listTransfersFromAccountStmt,
		listTransfersToAccountStmt:       q.listTransfersToAccountStmt,
		updateAccountStmt:                q.updateAccountStmt,
		updateEntryStmt:                  q.updateEntryStmt,
		updateTransferStmt:               q.updateTransferStmt,
	}
}
